// TODO: Add your app's Go model type definitions here
// These are auto-generated by Wails from your Go structs
// Example:
//
// export namespace mypackage {
//   export class MyModel {
//     ID: number;
//     name: string;
//     static createFrom(source: any = {}) { return new MyModel(source); }
//     constructor(source: any = {}) {
//       if ('string' === typeof source) source = JSON.parse(source);
//       this.ID = source["ID"];
//       this.name = source["name"];
//     }
//   }
// }
