// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {harness} from '../models';

export function CreateProfile(arg1:db.CreateProfileRequest):Promise<db.HarnessProfileFull>;

export function DeleteProfile(arg1:number):Promise<void>;

export function DuplicateProfile(arg1:number,arg2:string):Promise<db.HarnessProfileFull>;

export function ExportProfile(arg1:number,arg2:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetPresets():Promise<Array<harness.Preset>>;

export function GetProfile(arg1:number):Promise<db.HarnessProfileFull>;

export function ImportFromSettings(arg1:string):Promise<db.HarnessProfileFull>;

export function ImportPreset(arg1:string):Promise<db.HarnessProfileFull>;

export function ListProfiles():Promise<Array<db.HarnessProfile>>;

export function OpenDirectoryPicker():Promise<string>;

export function OpenSettingsFilePicker():Promise<string>;

export function PreviewExport(arg1:number):Promise<string>;

export function Quit():Promise<void>;

export function UpdateProfile(arg1:number,arg2:db.UpdateProfileRequest):Promise<db.HarnessProfileFull>;
