// @ts-check
// This file is automatically generated. DO NOT EDIT (will be overwritten by wails build/dev)

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function GetProfile(id) {
  return window['go']['main']['App']['GetProfile'](id);
}

export function CreateProfile(req) {
  return window['go']['main']['App']['CreateProfile'](req);
}

export function UpdateProfile(id, req) {
  return window['go']['main']['App']['UpdateProfile'](id, req);
}

export function DeleteProfile(id) {
  return window['go']['main']['App']['DeleteProfile'](id);
}

export function DuplicateProfile(id, newName) {
  return window['go']['main']['App']['DuplicateProfile'](id, newName);
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function ImportPreset(presetID) {
  return window['go']['main']['App']['ImportPreset'](presetID);
}

export function ExportProfile(id, targetPath) {
  return window['go']['main']['App']['ExportProfile'](id, targetPath);
}

export function ImportFromSettings(settingsPath) {
  return window['go']['main']['App']['ImportFromSettings'](settingsPath);
}

export function PreviewExport(id) {
  return window['go']['main']['App']['PreviewExport'](id);
}

export function OpenSettingsFilePicker() {
  return window['go']['main']['App']['OpenSettingsFilePicker']();
}

export function OpenDirectoryPicker() {
  return window['go']['main']['App']['OpenDirectoryPicker']();
}
