// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion(): Promise<string>;

export function OpenFilePicker(): Promise<string>;

export function Quit(): Promise<void>;

// TODO: Add your app's Go binding type declarations here
