// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DuplicateProfile(arg1, arg2) {
  return window['go']['main']['App']['DuplicateProfile'](arg1, arg2);
}

export function ExportProfile(arg1, arg2) {
  return window['go']['main']['App']['ExportProfile'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function ImportFromSettings(arg1) {
  return window['go']['main']['App']['ImportFromSettings'](arg1);
}

export function ImportPreset(arg1) {
  return window['go']['main']['App']['ImportPreset'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function OpenDirectoryPicker() {
  return window['go']['main']['App']['OpenDirectoryPicker']();
}

export function OpenSettingsFilePicker() {
  return window['go']['main']['App']['OpenSettingsFilePicker']();
}

export function PreviewExport(arg1) {
  return window['go']['main']['App']['PreviewExport'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}
